// js/Fisica/Segundo-parcial/Tema6/structure.js

import { showModal } from '../../../ui/modal.js';
import { dclLibrary } from './dcl-visuals/dcl-library.js';

// --- DATOS DE LOS EJERCICIOS ---
const exercises = [
    { enunciado: "Un bloque de 15 kg es empujado por una fuerza F a 30° bajo la horizontal, acelera de 0 a 10 m/s en 4s. Si μₖ = 0.25, encuentre a, fₖ, F y N.", solucion: "<h4>Solución</h4><p><strong>Paso 1 (Aceleración):</strong> $a = \\Delta v / \\Delta t = (10 - 0) / 4 = 2.5 \\, m/s^2$.</p><p><strong>Paso 2 (Ecuaciones de Newton):</strong> Descomponemos F: $F_x = F\\cos(30^\\circ)$, $F_y = F\\sin(30^\\circ)$ (hacia abajo).</p><p>$\\sum F_y = N - P - F_y = 0 \\implies N = mg + F\\sin(30^\\circ)$.</p><p>$\\sum F_x = F_x - f_k = ma \\implies F\\cos(30^\\circ) - \\mu_k N = ma$.</p><p><strong>Paso 3 (Resolver Sistema):</strong> Sustituimos N en la ecuación X: $F\\cos(30^\\circ) - \\mu_k(mg + F\\sin(30^\\circ)) = ma$.</p><p>$F(0.866) - 0.25(15 \\cdot 9.8 + F \\cdot 0.5) = 15 \\cdot 2.5$.</p><p>$0.866F - 36.75 - 0.125F = 37.5 \\implies 0.741F = 74.25 \\implies F \\approx 100.2 \\, N$.</p><p><strong>Paso 4 (Calcular N y fₖ):</strong> $N = 147 + 100.2 \\cdot 0.5 = 197.1 \\, N$.</p><p>$f_k = \\mu_k N = 0.25 \\cdot 197.1 = 49.3 \\, N$.</p>" },
    { enunciado: "Un coche de 1200 kg está en una colina con μₛ = 0.8. Encuentre el ángulo máximo θₘₐₓ antes de deslizar.", solucion: "<h4>Solución</h4><p><strong>Porqué:</strong> En el ángulo máximo, la fuerza de fricción estática máxima iguala a la componente del peso que tira del coche hacia abajo del plano.</p><p><strong>Ecuaciones:</strong> $f_{s,max} = P_x \\implies \\mu_s N = mg\\sin(\\theta)$. Y $N = P_y = mg\\cos(\\theta)$.</p><p><strong>Cálculo:</strong> $\\mu_s mg\\cos(\\theta) = mg\\sin(\\theta) \\implies \\mu_s = \\tan(\\theta)$.</p><p>$\\theta_{max} = \\arctan(\\mu_s) = \\arctan(0.8) \\approx 38.7^\\circ$.</p>" },
    { enunciado: "Esfera de acero de 2kg en glicerina alcanza v_terminal = 0.5 m/s. Fₖ = bv. Encuentre P, E, b y a₀.", solucion: "<h4>Solución</h4><p><strong>P (Peso):</strong> $P = mg = 2 \\cdot 9.8 = 19.6 \\, N$.</p><p><strong>E (Empuje):</strong> $V_{esfera} = m/\\rho_{acero} = 2/7850 \\approx 2.55 \\times 10^{-4} m^3$.</p><p>$E = \\rho_{glicerina} V g = 1260 \\cdot (2.55 \\times 10^{-4}) \\cdot 9.8 \\approx 3.15 \\, N$.</p><p><strong>b (Coeficiente):</strong> En v_terminal, $\\sum F = 0 \\implies P - E - F_D = 0 \\implies P - E = bv_t$.</p><p>$19.6 - 3.15 = b(0.5) \\implies 16.45 = 0.5b \\implies b \\approx 32.9 \\, Ns/m$.</p><p><strong>a₀ (Aceleración inicial):</strong> En t=0, v=0, Fₖ=0. $\\sum F = P - E = ma_0$.</p><p>$16.45 = 2a_0 \\implies a_0 = 8.225 \\, m/s^2$.</p>" },
    { enunciado: "Paracaidista de 80kg (A=0.7m², C=1.0, ρ=1.2kg/m³). Encuentre v_terminal, Fₖ a v_t/2 y 'a' en ese instante.", solucion: "<h4>Solución</h4><p><strong>v_terminal:</strong> Ocurre cuando $F_D = P \\implies \\frac{1}{2}C\\rho Av_t^2 = mg$.</p><p>$v_t = \\sqrt{\\frac{2mg}{C\\rho A}} = \\sqrt{\\frac{2 \\cdot 80 \\cdot 9.8}{1.0 \\cdot 1.2 \\cdot 0.7}} \\approx 43.2 \\, m/s$.</p><p><strong>Fₖ a v_t/2:</strong> $F_D \\propto v^2$. Si la velocidad es la mitad, la fuerza de arrastre es $(1/2)^2 = 1/4$ de la fuerza de arrastre máxima (que es igual al peso).</p><p>$F_D = P/4 = (80 \\cdot 9.8)/4 = 196 \\, N$.</p><p><strong>Aceleración:</strong> $\\sum F = P - F_D = ma \\implies mg - mg/4 = ma \\implies \\frac{3}{4}mg = ma \\implies a = \\frac{3}{4}g \\approx 7.35 \\, m/s^2$.</p>" },
    { enunciado: "Coche de 1500kg en curva peraltada (r=80m, μₛ=0.4). Encuentre v_ideal, v_max y N a v_max.", solucion: "<h4>Solución</h4><p><strong>v_ideal (sin fricción):</strong> La componente horizontal de la Normal provee la fuerza centrípeta. $\\tan(\\theta) = v^2 / (gr) \\implies v_{ideal} = \\sqrt{gr\\tan(\\theta)}$. (Necesitaríamos $\\theta$ para un valor numérico).</p><p><strong>v_max (con fricción):</strong> Ahora la fricción (hacia abajo del peralte) ayuda. $\\sum F_x = N\\sin(\\theta) + f_s\\cos(\\theta) = mv^2/r$. $\\sum F_y = N\\cos(\\theta) - P - f_s\\sin(\\theta) = 0$. Resolviendo este sistema se encuentra $v_{max}$.</p>" },
    { enunciado: "Carrito de 500kg en montaña rusa (cima r=20m, valle r=25m). Encuentre v_max en cima, N en cima, a꜀ en valle, N en valle.", solucion: "<h4>Solución</h4><p><strong>v_max en cima:</strong> El contacto se pierde cuando $N=0$. En la cima, $\\sum F = P - N = mv^2/r$. Si $N=0$, $mg = mv^2/r \\implies v = \\sqrt{gr} = \\sqrt{9.8 \\cdot 20} = 14 \\, m/s$.</p><p><strong>N en cima a v/2:</strong> $v' = 7 \\, m/s$. $N = P - mv'^2/r = 500 \\cdot 9.8 - 500 \\cdot 7^2 / 20 = 4900 - 1225 = 3675 \\, N$.</p><p><strong>a꜀ en valle:</strong> $v_{valle} = 1.5v = 21 \\, m/s$. $a_c = v_{valle}^2 / r_{valle} = 21^2 / 25 = 17.64 \\, m/s^2$.</p><p><strong>N en valle:</strong> $\\sum F = N - P = ma_c \\implies N = P + ma_c = 4900 + 500 \\cdot 17.64 = 13720 \\, N$.</p>" },
    { enunciado: "Sistema de 3 masas: m₁=2kg en (0,4), m₂=3kg en (-3,-2). Colocar m₃=5kg para que el CM esté en (0,0).", solucion: "<h4>Solución</h4><p><strong>CM de m₁ y m₂:</strong> $x_{12} = \\frac{2(0)+3(-3)}{2+3} = -1.8$. $y_{12} = \\frac{2(4)+3(-2)}{2+3} = 0.4$.</p><p><strong>Posición de m₃:</strong> Para que el CM total sea (0,0): $M_{total}X_{CM} = m_1x_1+m_2x_2+m_3x_3 = 0$.</p><p>$0 = 2(0)+3(-3)+5(x_3) \\implies 0 = -9 + 5x_3 \\implies x_3 = 1.8$.</p><p>$0 = 2(4)+3(-2)+5(y_3) \\implies 0 = 8-6+5y_3 \\implies 0 = 2+5y_3 \\implies y_3 = -0.4$.</p><p><strong>Respuesta:</strong> m₃ debe colocarse en $(1.8, -0.4)$.</p>" },
    { enunciado: "Granada de 3kg explota en su apogeo. v₀=(10î+20ĵ). m₁=1kg, v₁=(-5î+10ĵ). Encuentre t_cima, v_cm, m₂, v₂, a_cm.", solucion: "<h4>Solución</h4><p><strong>t_cima:</strong> $v_y = v_{0y} - gt \\implies 0 = 20 - 9.8t \\implies t \\approx 2.04 \\, s$.</p><p><strong>v_cm en apogeo:</strong> La velocidad del CM solo es afectada por fuerzas externas (gravedad). En el apogeo, $v_y=0$. $v_{cm} = v_x \\hat{i} = 10\\hat{i} \\, m/s$.</p><p><strong>m₂:</strong> $m_2 = M_{total} - m_1 = 3 - 1 = 2 \\, kg$.</p><p><strong>v₂:</strong> Se conserva el momento (o la velocidad del CM). $Mv_{cm} = m_1v_1 + m_2v_2$.</p><p>$3(10\\hat{i}) = 1(-5\\hat{i}+10\\hat{j}) + 2v_2 \\implies 30\\hat{i} = -5\\hat{i}+10\\hat{j} + 2v_2$.</p><p>$2v_2 = 35\\hat{i} - 10\\hat{j} \\implies v_2 = (17.5\\hat{i} - 5\\hat{j}) \\, m/s$.</p><p><strong>a_cm después:</strong> La única fuerza externa sigue siendo la gravedad. $a_{cm} = \\vec{g} = -9.8\\hat{j} \\, m/s^2$.</p>" },
    { enunciado: "Objeto de 2kg con F=-10x parte del reposo en x=1m. Use Euler (Δt=0.1s) para 2 pasos.", solucion: "<h4>Solución Numérica</h4><p><strong>Paso 0 (t=0):</strong> $x_0=1, v_0=0$. $a_0 = F/m = -10(1)/2 = -5 \\, m/s^2$.</p><p><strong>Paso 1 (t=0.1s):</strong> $v_1 = v_0 + a_0\\Delta t = 0 + (-5)(0.1) = -0.5 \\, m/s$.</p><p>$x_1 = x_0 + v_0\\Delta t = 1 + 0(0.1) = 1 \\, m$.</p><p><strong>Paso 2 (t=0.2s):</strong> $a_1 = -10(x_1)/2 = -10(1)/2 = -5 \\, m/s^2$.</p><p>$v_2 = v_1 + a_1\\Delta t = -0.5 + (-5)(0.1) = -1.0 \\, m/s$.</p><p>$x_2 = x_1 + v_1\\Delta t = 1 + (-0.5)(0.1) = 0.95 \\, m$.</p>" },
    { enunciado: "Pelota de 0.5kg lanzada a 30m/s hacia arriba. Fₖ=-0.1v². Use Euler (Δt=0.2s) para 1 paso.", solucion: "<h4>Solución Numérica</h4><p><strong>Paso 0 (t=0):</strong> $y_0=0, v_0=30$.</p><p><strong>Fuerza Neta:</strong> $F_0 = -mg - 0.1v_0^2 = -0.5(9.8) - 0.1(30)^2 = -4.9 - 90 = -94.9 \\, N$.</p><p><strong>Aceleración:</strong> $a_0 = F_0/m = -94.9 / 0.5 = -189.8 \\, m/s^2$.</p><p><strong>Paso 1 (t=0.2s):</strong> $v_1 = v_0 + a_0\\Delta t = 30 + (-189.8)(0.2) = 30 - 37.96 = -7.96 \\, m/s$.</p><p>$y_1 = y_0 + v_0\\Delta t = 0 + 30(0.2) = 6 \\, m$.</p>" },
    // ***** LA COMA QUE FALTABA ESTÁ AQUÍ *****
    { enunciado: "Bloque m₁=4kg sobre mesa giratoria (r=0.5m, μₛ=0.7). Encuentre ωₘₐₓ, vₜ y fₛ a ωₘₐₓ/2.", solucion: "<h4>Solución</h4><p><strong>Porqué:</strong> La fuerza centrípeta necesaria para mantener el bloque en círculo es provista por la fricción estática.</p><p><strong>ωₘₐₓ:</strong> La velocidad máxima ocurre cuando se necesita la máxima fricción estática. $f_{s,max} = m\\omega^2r \\implies \\mu_s N = m\\omega_{max}^2r$. Como $N=mg$, tenemos $\\mu_s mg = m\\omega_{max}^2r$.</p><p>$\\omega_{max} = \\sqrt{\\frac{\\mu_s g}{r}} = \\sqrt{\\frac{0.7 \\cdot 9.8}{0.5}} \\approx 3.7 \\, rad/s$.</p><p><strong>vₜ:</strong> $v_t = \\omega_{max}r = 3.7 \\cdot 0.5 = 1.85 \\, m/s$.</p><p><strong>fₛ a ω/2:</strong> A la mitad de la velocidad angular, la fricción estática no está al máximo, solo provee la fuerza necesaria. $\\omega' = 1.85 \\, rad/s$.</p><p>$f_s = m(\\omega')^2r = 4 \\cdot (1.85)^2 \\cdot 0.5 \\approx 6.85 \\, N$.</p>" },
    { enunciado: "Péndulo cónico (m=2kg, L=1.5m) gira con v=3m/s. Encuentre r, a꜀, θ y T.", solucion: "<h4>Solución</h4><p><strong>Ecuaciones:</strong> $\\sum F_y = T\\cos(\\theta) - mg = 0$. $\\sum F_x = T\\sin(\\theta) = ma_c = mv^2/r$. También, $r = L\\sin(\\theta)$.</p><p><strong>Resolver:</strong> Sustituimos r: $T\\sin(\\theta) = mv^2/(L\\sin(\\theta)) \\implies T = mv^2/(L\\sin^2(\\theta))$.</p><p>Sustituimos T en la ecuación Y: $\\frac{mv^2}{L\\sin^2(\\theta)}\\cos(\\theta) = mg \\implies \\frac{v^2}{gL} = \\frac{\\sin^2(\\theta)}{\\cos(\\theta)}$. Esta es una ecuación trascendente para $\\theta$. Una vez hallado $\\theta$, se encuentran r, T y a꜀.</p>" },
    { enunciado: "Dos patinadores (m₁=60kg en x=-5, m₂=90kg en x=10) se halan. Encuentre x_cm, a_cm y punto de encuentro.", solucion: "<h4>Solución</h4><p><strong>x_cm inicial:</strong> $x_{cm} = \\frac{60(-5) + 90(10)}{60+90} = \\frac{-300+900}{150} = \\frac{600}{150} = 4 \\, m$.</p><p><strong>a_cm:</strong> La fuerza de la cuerda es interna al sistema. No hay fuerzas externas horizontales. Por lo tanto, $a_{cm} = 0$. El centro de masas no se mueve.</p><p><strong>Punto de encuentro:</strong> Como el centro de masas no se mueve, se encontrarán en la posición inicial del centro de masas. Se encontrarán en $x = 4 \\, m$.</p>" },
    { enunciado: "Coche de 1000kg en cima parabólica (R=100m) a 15m/s, frenando con aₜ=-2m/s². Encuentre aₙ, a_total, f y N.", solucion: "<h4>Solución</h4><p><strong>aₙ (normal):</strong> $a_n = v^2/R = 15^2 / 100 = 2.25 \\, m/s^2$.</p><p><strong>a_total:</strong> $|\\vec{a}| = \\sqrt{a_t^2 + a_n^2} = \\sqrt{(-2)^2 + (2.25)^2} \\approx 3.01 \\, m/s^2$.</p><p><strong>f (fricción):</strong> La fricción causa la aceleración tangencial. $\\sum F_t = -f = ma_t \\implies -f = 1000(-2) \\implies f = 2000 \\, N$.</p><p><strong>N (normal):</strong> $\\sum F_n = P - N = ma_n \\implies N = P - ma_n = 1000(9.8) - 1000(2.25) = 9800 - 2250 = 7550 \\, N$.</p>" },
    { enunciado: "Bloque de 5kg halado desde reposo (μₖ=0.3) por F=40N a 37°. Encuentre N, fₖ, a y d tras 3s.", solucion: "<h4>Solución</h4><p><strong>N:</strong> $\\sum F_y = N + F\\sin(37^\\circ) - mg = 0 \\implies N = 5(9.8) - 40(0.6) = 49 - 24 = 25 \\, N$.</p><p><strong>fₖ:</strong> $f_k = \\mu_k N = 0.3 \\cdot 25 = 7.5 \\, N$.</p><p><strong>a:</strong> $\\sum F_x = F\\cos(37^\\circ) - f_k = ma \\implies 40(0.8) - 7.5 = 5a \\implies 32 - 7.5 = 5a \\implies 24.5 = 5a \\implies a = 4.9 \\, m/s^2$.</p><p><strong>d:</strong> $d = v_0t + \\frac{1}{2}at^2 = 0 + \\frac{1}{2}(4.9)(3^2) = 22.05 \\, m$.</p>" },
    { enunciado: "Doble plano inclinado (m₁=3kg a 30°, m₂=5kg a 53°). Encuentre a, T, N₁, N₂ y a_cm,x.", solucion: "<h4>Solución</h4><p><strong>Fuerzas en competencia:</strong> $P_{1x} = 3(9.8)\\sin(30^\\circ) = 14.7 \\, N$. $P_{2x} = 5(9.8)\\sin(53^\\circ) \\approx 39.1 \\, N$. El sistema se moverá hacia la derecha.</p><p><strong>a:</strong> $F_{neta} = P_{2x} - P_{1x} = (m_1+m_2)a \\implies 39.1 - 14.7 = 8a \\implies a \\approx 3.05 \\, m/s^2$.</p><p><strong>T (DCL de m₁):</strong> $T - P_{1x} = m_1a \\implies T = 14.7 + 3(3.05) = 23.85 \\, N$.</p><p><strong>Normales:</strong> $N_1 = m_1g\\cos(30^\\circ) \\approx 25.5 \\, N$. $N_2 = m_2g\\cos(53^\\circ) \\approx 29.5 \\, N$.</p>" },
    { enunciado: "Cubeta de 2kg de agua en círculo vertical (r=1.2m). Encuentre v_min en cima, T en cima, T en fondo (a 6m/s), a꜀ en fondo.", solucion: "<h4>Solución</h4><p><strong>v_min en cima:</strong> Ocurre cuando T=0. $\\sum F = P + T = mv^2/r \\implies mg = mv_{min}^2/r \\implies v_{min} = \\sqrt{gr} = \\sqrt{9.8 \\cdot 1.2} \\approx 3.43 \\, m/s$.</p><p><strong>T en cima a v_min:</strong> $T=0 \\, N$.</p><p><strong>T en fondo a 6m/s:</strong> $\\sum F = T - P = mv^2/r \\implies T = mg + mv^2/r = 2(9.8) + 2(6^2)/1.2 = 19.6 + 60 = 79.6 \\, N$.</p><p><strong>a꜀ en fondo:</strong> $a_c = v^2/r = 6^2/1.2 = 30 \\, m/s^2$.</p>" },
    { enunciado: "Coche de 1200kg en curva plana (r=50m, μₛ=0.6). Encuentre N, fₛ,ₘₐₓ y vₘₐₓ.", solucion: "<h4>Solución</h4><p><strong>N:</strong> En una curva plana, $N=P=mg = 1200 \\cdot 9.8 = 11760 \\, N$.</p><p><strong>fₛ,ₘₐₓ:</strong> $f_{s,max} = \\mu_s N = 0.6 \\cdot 11760 = 7056 \\, N$.</p><p><strong>vₘₐₓ:</strong> La fricción provee la fuerza centrípeta. $f_{s,max} = mv_{max}^2/r$.</p><p>$7056 = 1200 v_{max}^2 / 50 \\implies v_{max} = \\sqrt{\\frac{7056 \\cdot 50}{1200}} \\approx 17.15 \\, m/s$.</p>" },
    { enunciado: "Niño (40kg) camina 3m en plataforma (20kg, 5m). Luego salta a 2m/s (relativo a plat.). Encuentre d_plat, V_p, V_n.", solucion: "<h4>Solución</h4><p><strong>CM:</strong> El CM no se mueve. $m_n\\Delta x_n + m_p\\Delta x_p = 0$. El niño se mueve 3m relativo a la plataforma, $\\Delta x_{n,rel} = 3$. $\\Delta x_n = \\Delta x_p + 3$.</p><p><strong>d_plat:</strong> $40(\\Delta x_p + 3) + 20\\Delta x_p = 0 \\implies 60\\Delta x_p = -120 \\implies \\Delta x_p = -2 \\, m$. La plataforma se mueve 2m hacia atrás.</p><p><strong>Salto (Conservación de Momento):</strong> $P_i=0$. $P_f = m_n v_n + m_p v_p = 0$. $v_n = v_p + v_{n,rel} = v_p - 2$.</p><p><strong>V_p:</strong> $40(v_p - 2) + 20v_p = 0 \\implies 60v_p = 80 \\implies v_p = 4/3 \\approx 1.33 \\, m/s$.</p><p><strong>V_n:</strong> $v_n = 1.33 - 2 = -0.67 \\, m/s$.</p>" },
    { enunciado: "Ejercicio 20 (Simulación Numérica Conceptual): Explica los pasos de Euler para un objeto de 1kg con Fₖ = 0.2v².", solucion: "<h4>Solución Conceptual</h4><p><strong>Paso 0 (Setup):</strong> Definir constantes: $m=1, g=9.8, k=0.2, \\Delta t=1$. Condiciones iniciales: $t_0=0, y_0=0, v_0=0$.</p><p><strong>Paso 1 (Iteración 1, t=0s):</strong></p><p>1. Calcular Fuerza Neta: $F_0 = mg - kv_0^2 = 9.8 - 0.2(0)^2 = 9.8 \\, N$.</p><p>2. Calcular Aceleración: $a_0 = F_0/m = 9.8/1 = 9.8 \\, m/s^2$.</p><p>3. Estimar nueva velocidad y posición: $v_1 = v_0 + a_0\\Delta t = 0 + 9.8(1) = 9.8 \\, m/s$.</p><p>$y_1 = y_0 + v_0\\Delta t = 0 + 0(1) = 0 \\, m$. (Mejora de Euler-Cromer usaría $y_1 = y_0 + v_1\\Delta t$).</p><p><strong>Paso 2 (Iteración 2, t=1s):</strong></p><p>1. Calcular Fuerza Neta: $F_1 = mg - kv_1^2 = 9.8 - 0.2(9.8)^2 \\approx 9.8 - 19.2 = -9.4 \\, N$.</p><p>2. Calcular Aceleración: $a_1 = F_1/m = -9.4 \\, m/s^2$.</p><p>3. Estimar: $v_2 = v_1 + a_1\\Delta t = 9.8 - 9.4(1) = 0.4 \\, m/s$.</p><p>...y así sucesivamente hasta llegar a t=5s.</p>" }
];

export const tema = {
    title: "Ejercicios Avanzados de Dinámica",
    getHTML: () => {
        let html = '';
        exercises.forEach((ex, index) => {
            const i = index + 1;
            html += `
                <div class="solved-exercise-visual">
                    <div class="exercise-content">
                        <h4>Ejercicio ${i}</h4>
                        <p class="enunciado">${ex.enunciado}</p>
                        <button class="btn btn-solution" data-solution-id="sol-dinamica-adv-${i}">Ver Solución y DCL</button>
                        <div id="sol-dinamica-adv-${i}" class="solution-content">${ex.solucion}</div>
                    </div>
                    <div class="exercise-canvas-container">
                        <canvas id="canvas-ex-${i}" class="exercise-canvas" width="300" height="250"></canvas>
                    </div>
                </div>
            `;
        });
        return html;
    },
    init: () => {
        document.querySelectorAll('.btn-solution').forEach(button => {
            button.addEventListener('click', () => {
                const solutionId = button.dataset.solutionId;
                const solutionContent = document.getElementById(solutionId);
                if (solutionContent) {
                    showModal(solutionContent.innerHTML);
                }
            });
        });
        
        document.querySelectorAll('.exercise-canvas').forEach(canvas => {
            const ctx = canvas.getContext('2d');
            ctx.font = 'bold 14px Oswald';
            ctx.fillStyle = '#333';
            ctx.textAlign = 'center';
            ctx.textBaseline = 'middle';
            
            const exerciseId = canvas.id.replace('canvas-ex-', '');
            const functionName = `drawEx${exerciseId}`;
            
            if (dclLibrary[functionName]) {
                dclLibrary[functionName](ctx);
            } else {
                ctx.fillText('DCL no implementado', 150, 125);
            }
        });
    }
};